document.addEventListener('DOMContentLoaded', () => {
      const ui = {
          menuBtn: document.getElementById('menuBtn'),
              menu: document.getElementById('menu'),
                  accessBtn: document.getElementById('accessBtn'),
                      accessPanel: document.getElementById('accessPanel'),
                          fontPlus: document.getElementById('fontPlus'),
                              fontMinus: document.getElementById('fontMinus'),
                                  contrastBtn: document.getElementById('contrastBtn'),
                                      curiosidadeBtn: document.getElementById('curiosidadeBtn'),
                                          curiosidadeTexto: document.getElementById('curiosidadeTexto'),
                                              quizBox: document.getElementById('quizBox'),
                                                  quizBtn: document.getElementById('quizBtn'),
                                                      quizResultado: document.getElementById('quizResultado'),
                                                          slideImg: document.getElementById('slideImg'),
                                                              slideCaption: document.getElementById('slideCaption'),
                                                                  prevSlide: document.getElementById('prevSlide'),
                                                                      nextSlide: document.getElementById('nextSlide'),
                                                                          toggleTexto: document.getElementById('toggleTexto'),
                                                                              toggleCards: document.querySelectorAll('.toggle-card')
                                                                                };

                                                                                  const state = {
                                                                                      fontSize: 16,
                                                                                          contrast: false,
                                                                                              slideIndex: 0,
                                                                                                  autoplayId: null,
                                                                                                      reducedMotion: window.matchMedia('(prefers-reduced-motion: reduce)').matches
                                                                                                        };

                                                                                                          const slides = [
                                                                                                              { src: 'img/Campo.png', cap: 'Cultivo da cevada no campo.' },
                                                                                                                  { src: 'img/Malte.png', cap: 'Transformação da cevada em malte.' },
                                                                                                                      { src: 'img/Cidade.png', cap: 'Conexão entre agro e cidade.' }
                                                                                                                        ];

                                                                                                                          const curiosidades = [
                                                                                                                              'A cevada é uma matéria-prima importante para a produção de malte.',
                                                                                                                                  'O uso consciente da água ajuda a reduzir impactos ambientais.',
                                                                                                                                      'A tecnologia no campo melhora eficiência e produtividade.',
                                                                                                                                          'A cadeia produtiva liga agricultura, indústria e consumo.',
                                                                                                                                              'Práticas sustentáveis fortalecem o futuro do agro.'
                                                                                                                                                ];

                                                                                                                                                  const quiz = [
                                                                                                                                                      {
                                                                                                                                                            q: 'A cevada faz parte de qual etapa inicial?',
                                                                                                                                                                  a: 'Campo',
                                                                                                                                                                        opts: ['Campo', 'Cidade', 'Loja']
                                                                                                                                                                            },
                                                                                                                                                                                {
                                                                                                                                                                                      q: 'O malte é resultado de qual processo?',
                                                                                                                                                                                            a: 'Transformação',
                                                                                                                                                                                                  opts: ['Transformação', 'Decoração', 'Venda']
                                                                                                                                                                                                      },
                                                                                                                                                                                                          {
                                                                                                                                                                                                                q: 'Qual prática é importante no projeto?',
                                                                                                                                                                                                                      a: 'Uso consciente da água',
                                                                                                                                                                                                                            opts: ['Uso consciente da água', 'Desperdício', 'Poluição']
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                  ];

                                                                                                                                                                                                                                    const setExpanded = (button, expanded) => {
                                                                                                                                                                                                                                        button.setAttribute('aria-expanded', String(expanded));
                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                            const closeMenu = () => {
                                                                                                                                                                                                                                                ui.menu.classList.remove('open');
                                                                                                                                                                                                                                                    setExpanded(ui.menuBtn, false);
                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                        const openMenu = () => {
                                                                                                                                                                                                                                                            ui.menu.classList.add('open');
                                                                                                                                                                                                                                                                setExpanded(ui.menuBtn, true);
                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                    const toggleMenu = () => {
                                                                                                                                                                                                                                                                        const isOpen = ui.menu.classList.contains('open');
                                                                                                                                                                                                                                                                            isOpen ? closeMenu() : openMenu();
                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                const openAccessPanel = () => {
                                                                                                                                                                                                                                                                                    ui.accessPanel.hidden = false;
                                                                                                                                                                                                                                                                                        setExpanded(ui.accessBtn, true);
                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                            const closeAccessPanel = () => {
                                                                                                                                                                                                                                                                                                ui.accessPanel.hidden = true;
                                                                                                                                                                                                                                                                                                    setExpanded(ui.accessBtn, false);
                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                        const toggleAccessPanel = () => {
                                                                                                                                                                                                                                                                                                            ui.accessPanel.hidden ? openAccessPanel() : closeAccessPanel();
                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                const renderSlides = () => {
                                                                                                                                                                                                                                                                                                                    const current = slides[state.slideIndex];
                                                                                                                                                                                                                                                                                                                        if (!current) return;
                                                                                                                                                                                                                                                                                                                            ui.slideImg.src = current.src;
                                                                                                                                                                                                                                                                                                                                ui.slideImg.alt = current.cap;
                                                                                                                                                                                                                                                                                                                                    ui.slideCaption.textContent = current.cap;
                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                        const goToSlide = (index) => {
                                                                                                                                                                                                                                                                                                                                            state.slideIndex = (index + slides.length) % slides.length;
                                                                                                                                                                                                                                                                                                                                                renderSlides();
                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                    const next = () => goToSlide(state.slideIndex + 1);
                                                                                                                                                                                                                                                                                                                                                      const prev = () => goToSlide(state.slideIndex - 1);

                                                                                                                                                                                                                                                                                                                                                        const startAutoplay = () => {
                                                                                                                                                                                                                                                                                                                                                            if (state.reducedMotion || slides.length < 2) return;
                                                                                                                                                                                                                                                                                                                                                                stopAutoplay();
                                                                                                                                                                                                                                                                                                                                                                    state.autoplayId = window.setInterval(next, 5000);
                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                        const stopAutoplay = () => {
                                                                                                                                                                                                                                                                                                                                                                            if (state.autoplayId) {
                                                                                                                                                                                                                                                                                                                                                                                  clearInterval(state.autoplayId);
                                                                                                                                                                                                                                                                                                                                                                                        state.autoplayId = null;
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                const randomCuriosity = () => {
                                                                                                                                                                                                                                                                                                                                                                                                    const index = Math.floor(Math.random() * curiosidades.length);
                                                                                                                                                                                                                                                                                                                                                                                                        ui.curiosidadeTexto.textContent = curiosidades[index];
                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                            const buildQuiz = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                const fragment = document.createDocumentFragment();

                                                                                                                                                                                                                                                                                                                                                                                                                    quiz.forEach((item, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                          const card = document.createElement('article');
                                                                                                                                                                                                                                                                                                                                                                                                                                card.className = 'card';
                                                                                                                                                                                                                                                                                                                                                                                                                                      card.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                              <p><strong>${i + 1}. ${item.q}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ${item.opts.map((option, optIndex) => `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="radio" name="q${i}" value="${option}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${option}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `).join('')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fragment.appendChild(card);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ui.quizBox.appendChild(fragment);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const scoreQuiz = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      let score = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          quiz.forEach((item, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const selected = document.querySelector(`input[name="q${i}"]:checked`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (selected && selected.value === item.a) score += 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const feedback =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    score === quiz.length
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? 'Excelente! Você dominou o conteúdo.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : score >= 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? 'Muito bom! Você está quase lá.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : 'Continue explorando o site para aprender mais.';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ui.quizResultado.textContent = `Você acertou ${score} de ${quiz.length}. ${feedback}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const updateFont = (delta) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state.fontSize = Math.min(24, Math.max(12, state.fontSize + delta));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.documentElement.style.fontSize = `${state.fontSize}px`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const toggleContrast = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                state.contrast = !state.contrast;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.body.classList.toggle('high-contrast', state.contrast);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ui.menuBtn.addEventListener('click', toggleMenu);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ui.accessBtn.addEventListener('click', toggleAccessPanel);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ui.fontPlus.addEventListener('click', () => updateFont(2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ui.fontMinus.addEventListener('click', () => updateFont(-2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ui.contrastBtn.addEventListener('click', toggleContrast);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ui.curiosidadeBtn.addEventListener('click', randomCuriosity);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ui.quizBtn.addEventListener('click', scoreQuiz);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ui.prevSlide.addEventListener('click', prev);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ui.nextSlide.addEventListener('click', next);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ui.toggleCards.forEach((card) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              card.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ui.toggleTexto.textContent = card.dataset.text || '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.addEventListener('keydown', (event) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (event.key === 'Escape') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      closeMenu();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            closeAccessPanel();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener('click', (event) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const clickedInsideMenu = ui.menu.contains(event.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const clickedMenuBtn = ui.menuBtn.contains(event.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!clickedInsideMenu && !clickedMenuBtn && ui.menu.classList.contains('open')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      closeMenu();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const clickedInsideAccess = ui.accessPanel.contains(event.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const clickedAccessBtn = ui.accessBtn.contains(event.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!clickedInsideAccess && !clickedAccessBtn && !ui.accessPanel.hidden) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            closeAccessPanel();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    window.addEventListener('visibilitychange', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (document.hidden) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              stopAutoplay();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        startAutoplay();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                buildQuiz();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderSlides();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    startAutoplay();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
